apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: comp-test
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: comp-test
    app.kubernetes.io/part-of: rsenvapp
  name: comp-testsoeg
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: comp-test
    weight: null
status: {}
